spring:
  application:
    name: sell-course
  datasource:
    url: jdbc:postgresql://db:5432/sell-course
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:12345}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        id:
          new_generator_mappings: false
    open-in-view: false
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  data:
    redis:
      database: 0
      host: redis-v1
      port: 6379
      timeout: 60000
      password: 123456
  mail:
    host: smtp.gmail.com
    port: 587
    username: hieunm15402@gmail.com
    password: uizi nbvl tmjm vecr
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  kafka:
    bootstrap-servers: kafka-v1:9092
    consumer:
      group-id: my-consumer-group
      auto-offset-reset: earliest
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
jwt:
  signer-key: "ND3qj84pmAajX15lYhfKNVCxtmYdf5bg"
  valid-duration: 2
  refreshable-duration: 7
server:
  port: 8081
cloudinary:
  cloud-name: "dksz6cw9r"
  api-key: "855524113383431"
  api-secret: "94t2_RVAMLHRamLqLYejjm6kSl0"

